hotel = input('Digite o nome do hotel: ')
cidade = input('Digite o nome do cidade: ')
estrela = int(input('Informe a quantidade de estrelas de 1 a 5: '))

# print('*****'(hotel)'*****\n','*****'(cidade)'*****\n','******'(estrela)-'*****')
print('*'*20)
print('*'*7+hotel+'*'*7)
print('*'*7+cidade+'*'*7)
print('*'*9 + str(estrela)+'*'*10)
print('*'*20)
